services:
  frontend:
    image: lab7/frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:80
    environment:
      DB_HOST: database
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT:-3308}
    depends_on:
      - database
    develop:
      watch:
        - path: ./src
          target: /var/www/html/
          action: sync

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3308:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - ./db_data:/var/lib/mysql
